INSERT INTO `roles` (`id`, `description`, `name`) VALUES (NULL, 'rol para los usuarios administradores', 'ROLE_ADMIN');
INSERT INTO `roles` (`id`, `description`, `name`) VALUES  (NULL, 'rol para los usuarios del ebook', 'ROLE_USER');

INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Afganistán', 'Afgano', 'AFG');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Albania', 'Albanés', 'ALB');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Alemania', 'Alemán', 'DEU');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Andorra', 'Andorrano', 'AND');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Angola', 'Angoleño', 'AGO');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Antigua y Barbuda', 'Antiguano', 'ATG');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Arabia Saudita', 'Saudí', 'SAU');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Argelia', 'Argelino', 'DZA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Argentina', 'Argentino', 'ARG');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Armenia', 'Armenio', 'ARM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Australia', 'Australiano', 'AUS');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Austria', 'Austriaco', 'AUT');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Azerbaiyán', 'Azerbaiyano', 'AZE');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Bahamas', 'Bahameño', 'BHS');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Bangladés', 'Bangladesí', 'BGD');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Barbados', 'Barbadense', 'BRB');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Bélgica', 'Belga', 'BEL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Belice', 'Beliceño', 'BLZ');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Bielorrusia', 'Bielorruso', 'BLR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Bolivia', 'Boliviano', 'BOL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Bosnia y Herzegovina', 'Bosnio', 'BIH');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Botsuana', 'Botsuano', 'BWA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Brasil', 'Brasileño', 'BRA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Brunéi', 'Bruneano', 'BRN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Bulgaria', 'Búlgaro', 'BGR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Burkina Faso', 'Burkinés', 'BFA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Burundi', 'Burundés', 'BDI');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Bután', 'Butanés', 'BTN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Cabo Verde', 'Caboverdiano', 'CPV');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Camboya', 'Camboyano', 'KHM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Camerún', 'Camerunés', 'CMR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Canadá', 'Canadiense', 'CAN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Catar', 'Catarí', 'QAT');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Chad', 'Chadiano', 'TCD');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Chile', 'Chileno', 'CHL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('China', 'Chino', 'CHN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Chipre', 'Chipriota', 'CYP');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Colombia', 'Colombiano', 'COL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Comoras', 'Comorense', 'COM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Corea del Norte', 'Norcoreano', 'PRK');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Corea del Sur', 'Surcoreano', 'KOR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Costa de Marfil', 'Marfileño', 'CIV');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Costa Rica', 'Costarricense', 'CRI');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Croacia', 'Croata', 'HRV');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Cuba', 'Cubano', 'CUB');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Dinamarca', 'Danés', 'DNK');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Dominica', 'Dominiqués', 'DMA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Ecuador', 'Ecuatoriano', 'ECU');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Egipto', 'Egipcio', 'EGY');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('El Salvador', 'Salvadoreño', 'SLV');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Emiratos Árabes Unidos', 'Emiratí', 'ARE');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Eritrea', 'Eritreo', 'ERI');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Eslovaquia', 'Eslovaco', 'SVK');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Eslovenia', 'Esloveno', 'SVN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('España', 'Español', 'ESP');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Estados Unidos', 'Estadounidense', 'USA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Estonia', 'Estonio', 'EST');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Etiopía', 'Etíope', 'ETH');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Filipinas', 'Filipino', 'PHL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Finlandia', 'Finlandés', 'FIN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Fiyi', 'Fiyiano', 'FJI');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Francia', 'Francés', 'FRA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Gabón', 'Gabonés', 'GAB');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Gambia', 'Gambiano', 'GMB');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Georgia', 'Georgiano', 'GEO');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Ghana', 'Ghanés', 'GHA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Granada', 'Granadino', 'GRD');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Grecia', 'Griego', 'GRC');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Guatemala', 'Guatemalteco', 'GTM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Guinea', 'Guineano', 'GIN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Guinea Ecuatorial', 'Ecuatoguineano', 'GNQ');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Guinea-Bisáu', 'Guineano', 'GNB');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Guyana', 'Guyanés', 'GUY');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Haití', 'Haitiano', 'HTI');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Honduras', 'Hondureño', 'HND');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Hungría', 'Húngaro', 'HUN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('India', 'Indio', 'IND');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Indonesia', 'Indonesio', 'IDN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Irak', 'Iraquí', 'IRQ');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Irán', 'Iraní', 'IRN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Irlanda', 'Irlandés', 'IRL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Islandia', 'Islandés', 'ISL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Islas Marshall', 'Marshalés', 'MHL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Islas Salomón', 'Salomonense', 'SLB');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Israel', 'Israelí', 'ISR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Italia', 'Italiano', 'ITA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Jamaica', 'Jamaiquino', 'JAM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Japón', 'Japonés', 'JPN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Jordania', 'Jordano', 'JOR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Kazajistán', 'Kazajo', 'KAZ');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Kenia', 'Keniata', 'KEN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Kirguistán', 'Kirguís', 'KGZ');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Kiribati', 'Kiribatiano', 'KIR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Kuwait', 'Kuwaití', 'KWT');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Laos', 'Laosiano', 'LAO');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Lesoto', 'Lesotense', 'LSO');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Letonia', 'Letón', 'LVA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Líbano', 'Libanés', 'LBN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Liberia', 'Liberiano', 'LBR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Libia', 'Libio', 'LBY');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Liechtenstein', 'Liechtensteiniano', 'LIE');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Lituania', 'Lituano', 'LTU');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Luxemburgo', 'Luxemburgués', 'LUX');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Macedonia del Norte', 'Macedonio', 'MKD');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Madagascar', 'Malgache', 'MDG');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Malasia', 'Malasio', 'MYS');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Malaui', 'Malauí', 'MWI');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Maldivas', 'Maldivo', 'MDV');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Malí', 'Maleniano', 'MLI');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Malta', 'Maltés', 'MLT');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Marruecos', 'Marroquí', 'MAR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Mauricio', 'Mauriciano', 'MUS');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Mauritania', 'Mauritano', 'MRT');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('México', 'Mexicano', 'MEX');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Micronesia', 'Micronesio', 'FSM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Moldavia', 'Moldavo', 'MDA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Mónaco', 'Monegasco', 'MCO');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Mongolia', 'Mongol', 'MNG');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Montenegro', 'Montenegrino', 'MNE');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Mozambique', 'Mozambiqueño', 'MOZ');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Namibia', 'Namibio', 'NAM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Nauru', 'Nauruano', 'NRU');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Nepal', 'Nepalí', 'NPL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Nicaragua', 'Nicaragüense', 'NIC');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Níger', 'Nigerino', 'NER');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Nigeria', 'Nigeriano', 'NGA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Noruega', 'Noruego', 'NOR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Nueva Zelanda', 'Neozelandés', 'NZL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Omán', 'Omaní', 'OMN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Países Bajos', 'Neerlandés', 'NLD');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Pakistán', 'Pakistaní', 'PAK');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Palaos', 'Palauano', 'PLW');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Palestina', 'Palestino', 'PSE');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Panamá', 'Panameño', 'PAN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Papúa Nueva Guinea', 'Papú', 'PNG');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Paraguay', 'Paraguayo', 'PRY');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Perú', 'Peruano', 'PER');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Polonia', 'Polaco', 'POL');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Portugal', 'Portugués', 'PRT');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Reino Unido', 'Británico', 'GBR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('República Centroafricana', 'Centroafricano', 'CAF');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('República Checa', 'Checo', 'CZE');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('República del Congo', 'Congoleño', 'COG');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('República Democrática del Congo', 'Congoleño', 'COD');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('República Dominicana', 'Dominicano', 'DOM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Ruanda', 'Ruandés', 'RWA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Rumania', 'Rumano', 'ROU');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Rusia', 'Ruso', 'RUS');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Samoa', 'Samoano', 'WSM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('San Cristóbal y Nieves', 'Kittsiano', 'KNA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('San Marino', 'Sanmarinense', 'SMR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('San Vicente y las Granadinas', 'Sanvicentino', 'VCT');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Santa Lucía', 'Santalucense', 'LCA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Santo Tomé y Príncipe', 'Santotomense', 'STP');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Senegal', 'Senegalés', 'SEN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Serbia', 'Serbio', 'SRB');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Seychelles', 'Seychellense', 'SYC');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Sierra Leona', 'Sierraleonés', 'SLE');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Singapur', 'Singapurense', 'SGP');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Siria', 'Sirio', 'SYR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Somalia', 'Somalí', 'SOM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Sri Lanka', 'Ceilanés', 'LKA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Suazilandia', 'Suazi', 'SWZ');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Sudáfrica', 'Sudafricano', 'ZAF');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Sudán', 'Sudanés', 'SDN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Sudán del Sur', 'Sursudanés', 'SSD');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Suecia', 'Sueco', 'SWE');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Suiza', 'Suizo', 'CHE');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Surinam', 'Surinamés', 'SUR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Tailandia', 'Tailandés', 'THA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Tanzania', 'Tanzano', 'TZA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Tayikistán', 'Tayiko', 'TJK');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Timor Oriental', 'Timorense', 'TLS');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Togo', 'Togolés', 'TGO');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Tonga', 'Tongano', 'TON');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Trinidad y Tobago', 'Trinitense', 'TTO');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Túnez', 'Tunecino', 'TUN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Turkmenistán', 'Turcomano', 'TKM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Turquía', 'Turco', 'TUR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Tuvalu', 'Tuvaluano', 'TUV');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Ucrania', 'Ucraniano', 'UKR');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Uganda', 'Ugandés', 'UGA');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Uruguay', 'Uruguayo', 'URY');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Uzbekistán', 'Uzbeko', 'UZB');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Vanuatu', 'Vanuatuense', 'VUT');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Venezuela', 'Venezolano', 'VEN');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Vietnam', 'Vietnamita', 'VNM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Yemen', 'Yemení', 'YEM');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Yibuti', 'Yibutiano', 'DJI');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Zambia', 'Zambiano', 'ZMB');
INSERT INTO `nationalities` (`name`, `demonym`, `iso_code`) VALUES ('Zimbabue', 'Zimbabuense', 'ZWE');


INSERT INTO `books` (`available`, `publication_date`, `id`, `synopsis`, `cover`, `isbn`, `publisher`, `title`) VALUES ('4', '1605-01-16', NULL, 'Las aventuras de un hidalgo que, influenciado por los libros de caballerías, decide convertirse en caballero andante y salir en busca de aventuras.', 'don_quijote.jpg', '978-1-56619-909-4', 'Francisco de Robles', 'Don Quijote de la Mancha'); 
INSERT INTO `books` (`available`, `publication_date`, `id`, `synopsis`, `cover`, `isbn`, `publisher`, `title`) VALUES ('5', '1943-04-06', NULL, 'La historia de un piloto que, tras un accidente en el desierto del Sahara, encuentra a un pequeño príncipe venido de otro planeta.', 'el_principito.jpg', '978-1-56619-909-5', 'Reynal & Hitchcock', 'El Principito');
INSERT INTO `books` (`available`, `publication_date`, `id`, `synopsis`, `cover`, `isbn`, `publisher`, `title`) VALUES ('3', '1967-05-30', NULL, 'Una novela que narra la historia de la familia Buendía a lo largo de varias generaciones en el pueblo ficticio de Macondo.', 'cien_anos_de_soledad.jpg', '978-1-56619-909-6', 'Editorial Sudamericana', 'Cien Años de Soledad');

INSERT INTO `authors` (`birth_date`, `created_at`, `id`, `updated_at`, `biography`, `image`, `lastname`, `name`, `nationality_id`) VALUES ('1900-06-29', '2025-09-09 19:39:08.000000', NULL, NULL, 'Fue un escritor y aviador francés, conocido principalmente por su obra El Principito.', 'Francés', 'de Saint-Exupéry', 'Antoine', '62');
INSERT INTO `authors` (`birth_date`, `created_at`, `id`, `updated_at`, `biography`, `image`, `lastname`, `name`, `nationality_id`) VALUES ('1927-03-06', '2025-09-09 19:39:08.000000', NULL, NULL, 'Fue un escritor, guionista y periodista colombiano, conocido por su obra Cien Años de Soledad.', 'Colombiano', 'García Márquez', 'Gabriel', '38');
INSERT INTO `authors` (`birth_date`, `created_at`, `id`, `updated_at`, `biography`, `image`, `lastname`, `name`, `nationality_id`) VALUES ('1547-10-09', '2025-09-09 19:39:08.000000', NULL, NULL, 'Fue un escritor español, conocido principalmente por su obra Don Quijote de la Mancha.', 'Español', 'de Cervantes', 'Miguel', '55');

INSERT INTO  `categories`( `id`, `name`, `description`) VALUES (NULL, 'Ficción', 'Libros de ficción que incluyen novelas, cuentos y relatos imaginativos.');
INSERT INTO  `categories`( `id`, `name`, `description`) VALUES (NULL, 'Clásicos', 'Obras literarias que han perdurado a lo largo del tiempo y son consideradas de gran valor cultural.');
INSERT INTO  `categories`( `id`, `name`, `description`) VALUES (NULL, 'Aventura', 'Libros que narran historias emocionantes y llenas de acción.');
INSERT INTO  `categories`( `id`, `name`, `description`) VALUES (NULL, 'Fantasía', 'Libros que presentan mundos imaginarios y elementos sobrenaturales.');
